### ISSUE TITLE
After updating kotlin version to 1.8.0 project doesn't compile

### ISSUE THREAD

**Issue by redbluenat** [twilio/twilio-verify-for-react-native#31]
After updating the Kotlin version to 1.8.0, the project doesn't compile

#### Description

RNTwilioVerifyModule  'when' expression must be exhaustive

#### Steps to Reproduce

1. Update the Kotlin version in the project
2. Compile the project

#### Expected Behavior

You need to add an else statement
info: https://stackoverflow.com/questions/72379996/how-to-fix-non-exhaustive-when-statements-on-sealed-class-interface-in-kotli

#### Versions

- buildToolsVersion = "31.0.0"
-  minSdkVersion = 24
- compileSdkVersion = 33
- targetSdkVersion = 33
- kotlin_version = "1.8.0"
- React native version 0.71

**Comment by yafuquen** [comment]
@redbluenat A fix for this was released in the 0.4.0 version

**Comment by kg-currenxie** [comment]
@redbluenat was this confirmed to be working? We have the same issue @yafuquen 

RN 0.70
```
        supportLibVersion = "33.0.0"
        buildToolsVersion = "33.0.0"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = '1.8.0'
```
package: `"@twilio/twilio-verify-for-react-native": "https://github.com/twilio/twilio-verify-for-react-native.git",`


error:
```

e: file:///Users/../node_modules/@twilio/twilio-verify-for-react-native/android/src/main/java/com/twilio/verify/reactnative/RNTwilioVerifyModule.kt:90:5 'when' expression must be exhaustive, add necessary 'null' branch or 'else' branch instead
e: file:///Users/../node_modules/@twilio/twilio-verify-for-react-native/android/src/main/java/com/twilio/verify/reactnative/RNTwilioVerifyModule.kt:141:5 'when' expression must be exhaustive, add necessary 'null' branch or 'else' branch instead

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':twilio_twilio-verify-for-react-native:compileDebugKotlin'.
```

**Comment by yafuquen** [comment]
@kg-currenxie You can check the else branch added to the reported `when` with issues: 
https://github.com/twilio/twilio-verify-for-react-native/blob/main/android/src/main/java/com/twilio/verify/reactnative/RNTwilioVerifyModule.kt#L90
https://github.com/twilio/twilio-verify-for-react-native/blob/main/android/src/main/java/com/twilio/verify/reactnative/RNTwilioVerifyModule.kt#L141

Could you please check you are using the [0.4.0](https://github.com/twilio/twilio-verify-for-react-native/releases/tag/0.4.0) version?

**Comment by kg-currenxie** [comment]
@yafuquen works now!

> "@twilio/twilio-verify-for-react-native": "https://github.com/twilio/twilio-verify-for-react-native.git"

i thought this would always update to the latest, but it didn't 😓 my bad, it was locked to 0.3.0
